### ISSUE TITLE
watch only accounts not being added to the total (needs discussion - unclear if issue or not)

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status-client#1019]
This needs discussion on whenever it should be behave like this (i.e should read only accounts count towards total balance?)

1. enable wallet and add watch only account 0xbbf0cc1c63f509d48a4674e270d26d80ccaf6022

result: total balance is not taking into account the read only account

**Comment by michaelsbradleyjr** [comment]
On Status mobile (at least on iOS in my personal experience) read only accounts definitely *do* count towards the total balance.

**Comment by iurimatias** [comment]
closing as per comment from @michaelsbradleyjr
