### ISSUE TITLE
Add support to ipns and swarm for ens addresses

### ISSUE THREAD

**Issue by richard-ramos** [status-im/nim-status-client#1068]
- [ ] Support swarm addresses, by decoding the content hash and pointing the browser addressBar to: "swarm-gateways.net/bzz:/...."
- [ ] Support ipns addresses by decoding the content hash and pointing the browser to "https://ipfs.status.im/ipfs/......../"

Currently there's only support for IPFS hashes obtained from the contentHash of an ens address

**Comment by richard-ramos** [comment]
- theswarm.eth is an example of swarm address pointing to https://swarm-gateways.net/bzz:/3461e202e4cbd5614890a9a6d54fea1c678586d7d83c157bd03c1fa8ef6804a4/

- ipns-test.eth  is pointing to https://gateway.ipfs.io/ipns/ipfs.io/

**Comment by michaelsbradleyjr** [comment]
Do you think it would be possible while having the browser load the resolved URL, the address bar continues to display the more human-friendly one, e.g. `theswarm.eth`?

**Comment by richard-ramos** [comment]
Yes. I added support for that in https://github.com/status-im/nim-status-client/pull/1070

**Comment by flexsurfer** [comment]
you can test `uniswap.eth` for ipns on mainnet
