### ISSUE TITLE
seed phrase modal UI fix

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status-client#1079]
The text area to write seedphrase requires a bottom padding, otherwise letters will be cut.

![NEPGYlD.png](https://images.zenhubusercontent.com/5ea70c756a44040e719bbf06/2a67f86c-3654-4e45-9fa4-3868d631bb20)

**Comment by jrainville** [comment]
I think that was already fixed. I'll test right now

**Comment by jrainville** [comment]
Closing as this was already fixed
