### ISSUE TITLE
bug: spaces are replaced by dash

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-status-client#1149]
Archlinux, KDE Desktop
Using the beta.2 appImage https://github.com/status-im/nim-status-client/releases/tag/beta.2

![image](https://user-images.githubusercontent.com/22738317/95438073-16d7a200-0956-11eb-99e7-be2887277c86.png)

Base fontconfig:
![image](https://user-images.githubusercontent.com/22738317/95438178-3bcc1500-0956-11eb-8a32-d5b832494466.png)

On QT5 5.15, KDE Plasma 5.19.5

**Comment by jrainville** [comment]
That's a bug with translations not being loaded correctly. It's probably the same issue as https://github.com/status-im/nim-status-client/issues/1137

**Comment by mratsim** [comment]
Closing duplicate
