### ISSUE TITLE
Transaction bubble status icon is wrong when address is shared

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/nim-status-client#1206]
When "accepting & sharing" an address for a user to send a transaction, the transaction bubble update its status to`Address shared`, however, the icon stays "pending":

<img width="216" alt="Screenshot 2020-10-19 at 18 52 51" src="https://user-images.githubusercontent.com/445106/96483177-4b900700-123c-11eb-8e34-2d9e2bc95f2b.png">

**Comment by emizzle** [comment]
I believe this is correct, according to the design: ![Imgur](https://imgur.com/xkChz4h.png)

**Comment by PascalPrecht** [comment]
@emizzle I think you're right. When the Address is received the design still shows a "pending" icon:
<img width="202" alt="Screenshot 2020-10-21 at 11 24 38" src="https://user-images.githubusercontent.com/445106/96700695-0381f900-1390-11eb-872f-bc0b1edb64f8.png">

Wonder if that's intended though... /cc @simonricoo

**Comment by PascalPrecht** [comment]
Even though it doesn't seem expected, all designs (also on mobile) keep the "pending" icon when the address/account is shared. I assume that's because the overall tx is still in a pending state.

Closing this one. Feel free to reopen if this is still a concern.
