### ISSUE TITLE
Profile Status updates

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status-client#1236]
https://github.com/status-im/status/issues/1

**Comment by iurimatias** [comment]
we need designs for this on desktop (cc: @simonricoo )

**Comment by simonricoo** [comment]
Designs for Status Updates: https://www.figma.com/file/n0NB83EpT076bc1xQBKdYg/%F0%9F%97%A3-Status-Updates%E2%8E%9CDesktop?node-id=1968%3A13644
<img width="871" alt="Screen Shot 2020-12-02 at 10 46 55" src="https://user-images.githubusercontent.com/52249767/100856449-b7949a80-348b-11eb-8ce3-d8718561bef5.png">
