### ISSUE TITLE
Notifications for transactions

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status-client#1237]
https://github.com/status-im/status/issues/5

- designs (cc: @simonricoo should this use the existing toaster messages ?)
- relevant: https://github.com/status-im/status-go/pull/2026

**Comment by simonricoo** [comment]
Can you provide me some more info? IDK what do you mean by ""notifications for transactions". Is it when you interact with browser or where at?

**Comment by jrainville** [comment]
This has already been done, but we've had issues with our Infura keys, so it's probably what is causing the issue. If we can confirm that we are using the paid Infura key and the transaction notifications do not appear, it means that there is a bug

**Comment by jrainville** [comment]
This is already done
