### ISSUE TITLE
Browser - Search engine & Eth Explorer

### ISSUE THREAD

**Issue by simonricoo** [status-im/nim-status-client#1255]
Design for Search engine & Eth Explorer + browser settings.
Figma (Search + Explorer) - https://www.figma.com/file/Lhg5cbN1HZiNMrVNddMzrQ/%F0%9F%A7%AD-Browser%E2%8E%9CDesktop?node-id=1938%3A3081

Figma (Settings) - https://www.figma.com/file/Lhg5cbN1HZiNMrVNddMzrQ/%F0%9F%A7%AD-Browser%E2%8E%9CDesktop?node-id=1873%3A910

**Search engine**
<img width="1380" alt="Screenshot 2020-10-28 at 10 00 16" src="https://user-images.githubusercontent.com/52249767/97414617-7f39f380-1904-11eb-978d-92622d6f4e68.png">

**Ethereum explorer**
Open an ethereum explorer (Ethscan / Ethplorer / Blockchair) after a transaction hash or an address is entered in the address bar. 
<img width="1394" alt="Screenshot 2020-10-28 at 10 00 19" src="https://user-images.githubusercontent.com/52249767/97414888-d50e9b80-1904-11eb-9408-1bafc530f955.png">

**Settings**
<img width="1169" alt="Screenshot 2020-10-28 at 10 00 04" src="https://user-images.githubusercontent.com/52249767/97415036-06876700-1905-11eb-9f5b-0931c562dbd6.png">

**Comment by hesterbruikman** [comment]
Any thoughts on what search engines and explorers to support?

- https://startpage.com/
- Duckduckgo
- Etherscan
- Ethplorer.io
- ...

**Comment by simonricoo** [comment]
I've included these:
<img width="587" alt="Screenshot 2020-11-02 at 11 22 32" src="https://user-images.githubusercontent.com/52249767/97857226-b4c44f80-1cfd-11eb-86fc-40fd3e796cb1.png">
