### ISSUE TITLE
display dialog to join a new public chat or 1 on 1

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status-client#127]
this is an intermediate step task, for now let's forget the dropdown and extract the existing functionality to join a chat from the search box to instead:
- clicking on the "+" opens a popup (https://doc.qt.io/qt-5/qml-qtquick-controls2-popup.html)
- the popup has an input field, to type a channel or a pubkey and a button to join
- typing a channel should join that channel, typing a pubkey should start a 1 on 1 chat

**Comment by richard-ramos** [comment]
Implemented with PRs #204, #205, #213, #216 and #218
