### ISSUE TITLE
Choose Browser Modal

### ISSUE THREAD

**Issue by simonricoo** [status-im/nim-status-client#1277]
Problem: When I click on link I want to be able to choose the browser the linking will be opened with...
Solution: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=3042%3A27932
<img width="726" alt="Screenshot 2020-11-03 at 13 05 28" src="https://user-images.githubusercontent.com/52249767/97983221-3fc44900-1dd5-11eb-8019-68677a57df9b.png">

Add this to Privacy & Security Settings: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=3048%3A27754
<img width="874" alt="Screenshot 2020-11-03 at 13 13 20" src="https://user-images.githubusercontent.com/52249767/97983963-5a4af200-1dd6-11eb-8a21-9da83f8d5906.png">

**Comment by michaelsbradleyjr** [comment]
This is a nice idea. I've been using [Choosy](https://www.choosyosx.com/) for many years and it's great! So I would want to be able to disable the Status app's own "browser chooser" since I don't want the effect doubled-up.
