### ISSUE TITLE
chat-not-a-contact text fix

### ISSUE THREAD

**Issue by simonricoo** [status-im/nim-status-client#1281]
Rename this to: **Not a contact**

<img width="682" alt="Screenshot_2020-11-03_at_15_56_16" src="https://user-images.githubusercontent.com/52249767/98000777-2929ec00-1ded-11eb-96d5-c992b6950635.png">

**Comment by hydr063n** [comment]
i think this has been fixed  
![2020-11-13-193421_182x84_scrot](https://user-images.githubusercontent.com/58890963/99102930-7117f280-25e7-11eb-8e2f-b9bf2837f922.png)

**Comment by PascalPrecht** [comment]
Yes, this gets fixed every time we run our i18n script
