### ISSUE TITLE
"Share your key" and "invite" links should have visible hover state

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/nim-status-client#1453]
<img width="495" alt="Screenshot 2020-12-02 at 11 55 38" src="https://user-images.githubusercontent.com/445106/100863751-4eb22000-3495-11eb-82a1-d09c1ce33d16.png">

Should be underlined when hovering and cursor should turn into pointer

**Comment by jinhojang6** [comment]
@PascalPrecht An ambassador wants to take this issue along with https://github.com/status-im/nim-status-client/issues/1455 . Can I have him start working on this?

**Comment by PascalPrecht** [comment]
Pity! Already sent a PR for this just today: https://github.com/status-im/nim-status-client/pull/1590

**Comment by jinhojang6** [comment]
Okay, thanks
