### ISSUE TITLE
fix: clicking the "down arrow" for long messages does not expand the message as expected

### ISSUE THREAD

**Issue by emizzle** [status-im/nim-status-client#1552]
Running image from PRhttps://github.com/status-im/nim-status-client/pull/1539#issuecomment-745551646, when a long message has been sent, the message height is clipped, and a down arrow is added to allow the user to expand the message to full height. 

Expected: clicking the down arrow will expand the message to its full height
Actual: Clicking this down arrow does nothing.

![imgur](https://imgur.com/TOIwsjJ.png)

**Comment by PascalPrecht** [comment]
This is fixed as of latest `master`

**Comment by jrainville** [comment]
I can't reproduce either on latest master. Gonna close
