### ISSUE TITLE
Delete chat button should follow designs

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/nim-status-client#1603]
The delete button of the Delete Chat Popup has a weird style mix of a standard/primary button and a warn button.

<img width="410" alt="Screenshot 2021-01-11 at 16 54 22" src="https://user-images.githubusercontent.com/445106/104204528-aac17a00-542d-11eb-85e5-a2a7957ab060.png">

**Comment by PascalPrecht** [comment]
Same goes for Remove Contact button

<img width="411" alt="Screenshot 2021-01-11 at 16 58 48" src="https://user-images.githubusercontent.com/445106/104205084-48b54480-542e-11eb-8caf-146b3c9a370a.png">

**Comment by PascalPrecht** [comment]
I believe we're using the same modal with different title and button labels here, but I might be wrong

**Comment by staked-smart-ace** [comment]
Could I work on this issue

**Comment by jrainville** [comment]
Yes. Assigning you

**Comment by staked-smart-ace** [comment]
ok, could you provide me proper design?

**Comment by jrainville** [comment]
Delete chat here: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=663%3A370

You can use the same style for the Remove
