### ISSUE TITLE
Nickname field isn't pre-filled with Nickname

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/nim-status-client#1604]
When a user is given a nickname and the profile popup for that user is opened again, the nickname field says "None", while there clearly is a Nickname.

<img width="473" alt="Screenshot 2021-01-11 at 17 00 47" src="https://user-images.githubusercontent.com/445106/104205340-8fa33a00-542e-11eb-95c8-5beccebcb005.png">

This should be hydrated with the chosen Nickname all the time.

**Comment by staked-smart-ace** [comment]
Can I try to fix this issue?
