### ISSUE TITLE
browser: add url bar

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status-client#161]
this is simple to do with qml, but we should investigate the current options since webengine does already support some of this UI

**Comment by richard-ramos** [comment]
Consider using: 
https://doc.qt.io/qt-5/qtwebengine-webengine-quicknanobrowser-example.html

**Comment by richard-ramos** [comment]
Needs to resolve ens addresses like simpledapp.eth or statusreferrals.eth.
