### ISSUE TITLE
Emoji messages are rendered too big

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/nim-status-client#1610]
When sending a single emoji message they are rendere quite huge
<img width="805" alt="Screenshot 2021-01-11 at 17 24 48" src="https://user-images.githubusercontent.com/445106/104209367-e9593380-5431-11eb-98e7-003d194002cd.png">
<img width="789" alt="Screenshot 2021-01-11 at 17 25 02" src="https://user-images.githubusercontent.com/445106/104209393-f118d800-5431-11eb-8fec-d71b36da4141.png">

Emoji mixed with text on the other hand do not
<img width="135" alt="Screenshot 2021-01-11 at 17 25 15" src="https://user-images.githubusercontent.com/445106/104209419-f8d87c80-5431-11eb-889b-5af44061172a.png">

**Comment by staked-smart-ace** [comment]
I am going to work on this issue

**Comment by staked-smart-ace** [comment]
I have a quick question at this moment.
What is your expected proper size of Emoji?

**Comment by jrainville** [comment]
I'm not exactly sure. @PascalPrecht or @simonricoo (our designer) could answer that

**Comment by jrainville** [comment]
From what I see on Figma, we probably aim for 22x22
Do you have access to our Figma files?
https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=616%3A0

**Comment by staked-smart-ace** [comment]
ok, let me check from the Figma

**Comment by staked-smart-ace** [comment]
According to the Figma design, it should be same as normal text box size (height)

**Comment by simonricoo** [comment]
Emoji + Text = Emoji is 22x22
Emojis only = Emoji is 32x32
You can find the example on the bottom of this artboard: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=566%3A23239
<img width="346" alt="Screenshot 2021-01-14 at 09 14 57" src="https://user-images.githubusercontent.com/52249767/104563225-ad002000-5649-11eb-8059-6d2c27eab433.png">
<img width="512" alt="Screenshot 2021-01-14 at 09 15 05" src="https://user-images.githubusercontent.com/52249767/104563228-ae314d00-5649-11eb-911a-17095f7983f5.png">
<img width="512" alt="Screenshot_2021-01-14_at_09_15_05" src="https://user-images.githubusercontent.com/52249767/104563234-affb1080-5649-11eb-9014-7fbd8e05b108.png">
