### ISSUE TITLE
Text selection color should match design

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/nim-status-client#1611]
Right now, in most places, text selection is rendered with a dark blue
<img width="199" alt="Screenshot 2021-01-11 at 17 27 53" src="https://user-images.githubusercontent.com/445106/104209703-57055f80-5432-11eb-9e69-93fcaa301ea6.png">

Check figma and adjust accordingly

**Comment by staked-smart-ace** [comment]
Could I work on this issue?
If so, please provide me right figma url to refer

**Comment by staked-smart-ace** [comment]
Should I update all of the edit boxs including chat history view?

**Comment by jrainville** [comment]
Let's ask @simonricoo on this one
