### ISSUE TITLE
Chat input should be completely round with no text

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/nim-status-client#1612]
At the moment, the default state of the chat input is to have a slight border radius but not quite 50%
<img width="143" alt="Screenshot 2021-01-11 at 17 28 55" src="https://user-images.githubusercontent.com/445106/104209838-7bf9d280-5432-11eb-83c1-36fcb3c8f8a4.png">

**Comment by staked-smart-ace** [comment]
Could I work on this issue?

**Comment by jrainville** [comment]
Assigned you @staked-smart-ace

**Comment by staked-smart-ace** [comment]
I am not sure about ```with no text``` in the issue subject. Could we make sure about this?

**Comment by jrainville** [comment]
I think it just means that all times, it should have a circle border like here: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=1919%3A23878

**Comment by jrainville** [comment]
Unless it has multiple lines like here: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=1920%3A378

**Comment by staked-smart-ace** [comment]
According to design, border-radius is static 36px (not 50%).
What do you think about this?

**Comment by jrainville** [comment]
That sounds right yeah

**Comment by staked-smart-ace** [comment]
And then, the code was also implemented correctly with 36px,
I just checked code lines.

**Comment by jrainville** [comment]
I think then it needs to be dynamic. If there is only one line of text, radius is 50% of the height.
if there are more than one line of text, then 36

**Comment by staked-smart-ace** [comment]
![chat-input](https://user-images.githubusercontent.com/29419562/104613713-ee6fea00-56a0-11eb-85be-a60143657638.png)
This is showing in my local, it seems to be differentt with @PascalPrecht 's attachment

**Comment by staked-smart-ace** [comment]
Could you also check yourself?

**Comment by jrainville** [comment]
Hmm, that's very weird. On my Linux and Wndows machines, I have this 
![image](https://user-images.githubusercontent.com/11926403/104614594-649b2f00-5656-11eb-9c11-51eed285fa8f.png)

So somehow your screen is correct and ours are not. Maybe it's because of the resolution?

**Comment by staked-smart-ace** [comment]
Are you on Mac?, I am in Win

**Comment by jrainville** [comment]
I use Windows and a Linux VM and both have the incorrect borders

**Comment by jrainville** [comment]
Since you can't reproduce, you can leave this issue for one of us and take another one in the meantime

**Comment by staked-smart-ace** [comment]
let me try to do with dynamic radius

**Comment by staked-smart-ace** [comment]
I need to check ```implicitHeight``` of the single line chat input box on your test env.
Could I add some debug code and commit so that you test it?

**Comment by jrainville** [comment]
I'm not sure what you mean. You want to test if you code works well on my machine since you can't reproduce yourself?
We don't actually have a test env.

Since you said you work on Windows, you should know that for some unknown reason, `console.log`s in QML don't print in the console. It's one of the reasons why I code in a VM

**Comment by staked-smart-ace** [comment]
The problem is that I can't reproduce this issue in my env

**Comment by staked-smart-ace** [comment]
I am gonna show implicitHeight value as a placeholder text of chat input box.

**Comment by jrainville** [comment]
Yeah, you can send your code so that we can test it, but if it doesn't work, it's probably better if one of us that can reproduce it fixes it, so that you can work on something else that you can test

**Comment by staked-smart-ace** [comment]
Do you want me to make PR with temp code or send code snippet directly?
When you confirm correct value, I can just fix this issue :)

**Comment by staked-smart-ace** [comment]
![image](https://user-images.githubusercontent.com/29419562/104643421-d8c0eb80-56c5-11eb-9605-adb440c22cc7.png)
This is code snippet.

**Comment by staked-smart-ace** [comment]
Now, I am expecting it will be 41~45 range

**Comment by jrainville** [comment]
It is `41` on my env

**Comment by staked-smart-ace** [comment]
Ok, let me fix this is right now :)
