### ISSUE TITLE
Channels should have muted state

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/nim-status-client#1615]
When a channel is muted, there's no visual indicator for that in the channel list.
I couldn't actually find designs for such a state, but I might have missed something. Looping in @simonricoo to confirm.

**Comment by simonricoo** [comment]
You are right, I just made the muted state here for:
**Compact mode**: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=4016%3A41161
**Normal mode**: https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=4016%3A41631
