### ISSUE TITLE
Setup CI builds for MacOS app

### ISSUE THREAD

**Issue by jakubgs** [status-im/nim-status-client#335]
The branch that currently works is [`macos-packaging-refactor`](https://github.com/status-im/nim-status-client/tree/chore/macos-packaging-refactor).
Apparently calling `make macos` should Just Work™.

We'll also need a setup on Jenkins to securely sign the app using a Keychain.

**Comment by jakubgs** [comment]
I have a two jobs here:

* https://ci.status.im/job/nim-status-client/job/linux/
* https://ci.status.im/job/nim-status-client/job/macos/

The work is happening in the [`ci-setup`](https://github.com/status-im/nim-status-client/tree/ci-setup) branch.

**Comment by jakubgs** [comment]
### Linux Notes

* Using Nix works, but getting the old `2.23` GLibc version would rebuild too much stuff to be feasible
* `a12e/docker-qt:5.14-gcc_64` docker image used in [`build-linux.sh`](https://github.com/status-im/nim-status-client/blob/master/build-linux.sh) is a good starting point
* With minimal adjustments I made a [`Dockerfile`](https://github.com/status-im/nim-status-client/blob/ci-setup/ci/Dockerfile) based off of it and pushed a [`nim-status-client-build`](https://hub.docker.com/r/statusteam/nim-status-client-build) image
* Use of `linuxdeployqt` fails with `fuse: mount failed: Permission denied` because of Docker user remapping
  - Adding of `--cap-add SYS_ADMIN --device /dev/fuse` fixes lack of `/dev/fuse` initially
* A `jenkins` user has to exist in the image with UID/GID set to `1001` due to how our hosts are set up

**Comment by jakubgs** [comment]
### MacOS Notes

* The installer DMG file for Qt cannot be installed without UI, but it's possible to tarball the resulting installation for CI setup
* I deployed a tarball like that in https://github.com/status-im/infra-ci/commit/314fc2d8 to all 3 CI hosts
* The `pkg-config` and `wget` packages need to be installed via Homebrew

**Comment by jakubgs** [comment]
For posterity this is a minimal Nix shell I created when researching:
```nix
{ pkgs ? import <nixpkgs> { 
  overlays = [{
    linuxdeployqt = super.callPackage ./nix/pkgs/linuxdeployqt { };
  }];
} }:

let
  inherit (pkgs) qt5 mkShell;

  # Custom collection of QT libraries for Status desktop App
  qtCustom = qt5.env "qt-custom-${qt5.qtbase.version}" (with qt5; [
    qtbase
    qtsvg
    qtdeclarative
    qtquick1
    qtquickcontrols2
  ]);

in mkShell {
  name = "nim-status-client-shell";
  buildInputs = with pkgs; [
    cmake pkg-config qtCustom linuxdeployqt
    # libraries
    pcre openssl mesa_glu
  ];

  QTDIR = qtCustom;
  QT5_PCFILEDIR = "${qtCustom}/lib/pkgconfig";
  QT5_LIBDIR = "${qtCustom}/lib";
}
```
I copied the derivation for `linuxdeployqt` from [status-react](https://github.com/status-im/status-react/tree/develop/nix/pkgs/linuxdeployqt).

**Comment by jakubgs** [comment]
I'm having a weird warnings on MacOS during build:
```
11:35:50  Package Qt5Core was not found in the pkg-config search path.
11:35:50  Perhaps you should add the directory containing `Qt5Core.pc'
11:35:50  to the PKG_CONFIG_PATH environment variable
11:35:50  No package 'Qt5Core' found
11:35:50  Package Qt5Qml was not found in the pkg-config search path.
11:35:50  Perhaps you should add the directory containing `Qt5Qml.pc'
11:35:50  to the PKG_CONFIG_PATH environment variable
11:35:50  No package 'Qt5Qml' found
11:35:50  Package Qt5Gui was not found in the pkg-config search path.
11:35:50  Perhaps you should add the directory containing `Qt5Gui.pc'
11:35:50  to the PKG_CONFIG_PATH environment variable
11:35:50  No package 'Qt5Gui' found
...
```
Although as far as I can tell I have a valid Qt installation.

**Comment by jakubgs** [comment]
Looks like using the [online Qt installer](http://download.qt.io/official_releases/online_installers/qt-unified-mac-x64-online.dmg) gives a more complete installation for some reason...

**Comment by jakubgs** [comment]
Also, the `QTDIR` needs to be set so that at it's root there's the architecture folder, like `gcc_64` or `clang_64`.

**Comment by jakubgs** [comment]
In order to fix the issues with Fuse permissions for Linux builds I might have to disable  [user remapping](https://docs.docker.com/engine/security/userns-remap/) for Docker on our hosts:
```
12:54:53  linuxdeployqt tmp/linux/dist/nim-status.desktop -no-translations -no-copy-copyright-files -qmldir=tmp/linux/dist/usr/ui -qmlimport=/opt/qt/5.14.0/gcc_64/qml -bundle-non-qt-libs
12:54:53  fuse: mount failed: Permission denied
12:54:53  open dir error: No such file or directory
12:54:53  Makefile:170: recipe for target 'pkg/NimStatusClient-x86_64.AppImage' failed
```
Which might be a pain because other jobs that use Docker might take that into account.
Although the only ones I can think of right now are [`status-go`](https://ci.status.im/job/status-go/job/platforms/job/xgo/) and [`keycard-cli`](https://ci.status.im/job/status-keycard/job/keycard-cli/) ones.

**Comment by jakubgs** [comment]
And it appears that `QT5_PCFILEDIR` and `QT5_LIBDIR` have to be set for `cmake` to detect Qt correctly:
```
13:06:07  CMake Warning at lib/CMakeLists.txt:7 (find_package):
13:06:07    By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
13:06:07    asked CMake to find a package configuration file provided by "Qt5", but
13:06:07    CMake did not find one.
13:06:07  
13:06:07    Could not find a package configuration file provided by "Qt5" with any of
13:06:07    the following names:
13:06:07  
13:06:07      Qt5Config.cmake
13:06:07      qt5-config.cmake
13:06:07  
13:06:07    Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
13:06:07    to a directory containing one of the above files.  If "Qt5" provides a
13:06:07    separate development package or SDK, be sure it has been installed.
13:06:07  Call Stack (most recent call first):
13:06:07    lib/CMakeLists.txt:71 (add_target)
```

**Comment by jakubgs** [comment]
I'm really confused by behavior of 2 MacOS hosts.
On `macos-03.ms-eu-dublin.ci.misc` setting `QTDIR=/usr/local/qt` is enough to `make nim_status_client`.
But on `macos-01.ms-eu-dublin.ci.misc` using the same `QTDIR=/usr/local/qt` results in a failure, sometimes. But setting it to `QTDIR=/usr/local/qt/clang_64` unblocks that failure for no good reason.

**Comment by jakubgs** [comment]
First successful MacOS build: https://ci.status.im/job/nim-status-client/job/macos/25
Except it's not actually successful, just that the failure is not registered:
```
16:26:12  ✖ Code signing failed. The DMG is fine, just not code signed.
16:26:12  No suitable code signing identity found
```
No next step is to get the keystore into Jenkins.

**Comment by jakubgs** [comment]
It might be possible to create a keychain with the certificate using CLI:
```
sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain <certificate>
```
https://apple.stackexchange.com/questions/80623/import-certificates-into-the-system-keychain-via-the-command-line

**Comment by jakubgs** [comment]
Almost there:
```
17:57:04  ERROR: Could not parse otool output line: "\t/System/Library/Frameworks/MediaPlayer.framework/Versions/A/MediaPlayer (compatibility version 1.0.0, current version 1.0.0, weak)"
17:57:05  ERROR: Could not parse otool output line: "\t/System/Library/Frameworks/MediaPlayer.framework/Versions/A/MediaPlayer (compatibility version 1.0.0, current version 1.0.0, weak)"
17:57:05  ERROR: Could not parse otool output line: "\t/System/Library/Frameworks/MediaPlayer.framework/Versions/A/MediaPlayer (compatibility version 1.0.0, current version 1.0.0, weak)"
17:57:07  ERROR: Could not parse otool output line: "\t/System/Library/Frameworks/MediaPlayer.framework/Versions/A/MediaPlayer (compatibility version 1.0.0, current version 1.0.0, weak)"
17:57:12  ****: no identity found
17:57:12  make: *** [pkg/Status.dmg] Error 1
```
It appears I might need both the private key and the cert in the keychain to make it work.

**Comment by jakubgs** [comment]
Yes, it looks like the best bet would be to:

1. Create a new Keychain
2. Create a new private key in that Keychain
3. Generate a CSR from that private key
4. Issue a new MacOS app signing certificate
5. Add that certificate to the Keychain

And then upload that Keychain to our CI credentials.
I'll do that tomorrow. I'll need to document the process too.

**Comment by jakubgs** [comment]
I created a new keychain and uploaded it to CI master, even made instructions on how I did it:
https://github.com/status-im/infra-docs/blob/master/articles/macos_signing_keychain.md
But for some reason I'm still getting:
```
 > codesign --sign "${IDENTITY_NAME}" \
      --keychain ~/nim-status-client.keychain-db \
      --options runtime --deep --force --verbose=4 \
      tmp/macos/dist/Status.app
Developer ID Application: STATUS HOLDINGS PTE. LTD. (DTX7Z4U3YA): no identity found
```

**Comment by jakubgs** [comment]
Okay, I see what was missing. I need to add the keychain to the search list too:
```
security list-keychains -s ${MACOS_KEYCHAIN_FILE}
```
But now it fails with:
```
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate: can't allocate code signature data for: /Users/jenkins/workspace/nim-status-client/macos/tmp/macos/dist/Status.app/Contents/MacOS/nim_status_client (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked using a larger -headerpad value)
tmp/macos/dist/Status.app: the codesign_allocate helper tool cannot be found or used
In subcomponent: /Users/jenkins/workspace/nim-status-client/macos/tmp/macos/dist/Status.app/Contents/MacOS/nim_status_client
```
Which is progress of a kind.

**Comment by jakubgs** [comment]
Not to self, `linuxdeployqt` has a `-unsupported-bundle-everything` flag which could let use use newer `glibc` while we work.

**Comment by jakubgs** [comment]
I tried setting `LDFLAGS=""` to fix the error:
```
codesign_allocate: can't allocate code signature data for: nim_status_client (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked using a larger -headerpad value)
```
But it didn't seem to work, but I found this:
>Will only be used by CMake on the first configuration to determine the default linker flags, after which the value for LDFLAGS is stored in the cache
https://cmake.org/cmake/help/v3.10/envvar/LDFLAGS.html

**Comment by jakubgs** [comment]
It might make sense to upgrade XCode from `11.4.1` to `11.5` just to make sure that's not the issue. I'll do that tomorrow.

**Comment by jakubgs** [comment]
Here's an interesting issue that goes more in-depth about the `can't allocate code signature data for` error:
https://trac.macports.org/ticket/39221

**Comment by jakubgs** [comment]
I ran the build on the one `macos-01` I upgraded to XCode `11.5` and the same error happens.

**Comment by jakubgs** [comment]
Another thing to try is instead of using `LDFLAGS` I could use `--passL:"-headerpad_max_install_names"` to try to give the suggested linker flag directly to `nim` compiler.

**Comment by jakubgs** [comment]
So I've confirmed the flag actually work by setting it directly in the makefile:
```makefile
NIM_PARAMS += --passL:"-headerpad_max_install_names"
```
And it worked in: https://ci.status.im/job/nim-status-client/job/macos/74/console
Now we have our good old friend `errSecInternalComponent`:
```
### Signing target...
tmp/macos/dist/Status.app: errSecInternalComponent
In subcomponent: /Users/jenkins/workspace/nim-status-client/macos/tmp/macos/dist/Status.app/Contents/MacOS/nim_status_client
```

**Comment by jakubgs** [comment]
I think this line is the issue:
https://github.com/status-im/nim-status-client/blob/7489a2ae0036aeaf4452ace44a81ebb65f7e29eb/Makefile#L97-L99
What it should look like is:
```Makefile
ifeq ($(detected_OS), Darwin)
NIM_PARAMS += -L:"-framework Foundation -framework Security -framework IOKit -framework CoreServices"
endif
```
Otherwise the value from the environment is not inherited properly.

**Comment by stefantalpalaru** [comment]
NIM_PARAMS should not be in the environment. That's NIMFLAGS territory.

The former is just a set of unchangeable options that the latter can add to: https://github.com/status-im/nimbus-build-system#nimflags

**Comment by jakubgs** [comment]
Why would you split those? What's the point? In a `Makefile` you can just append to an existing env variable using `+=`.
By splitting this variable into two variables you're making things more obscure and harder to follow while gaining nothing.

**Comment by stefantalpalaru** [comment]
Yes, it can use some refactoring, but it's high-cost and low-gain. Something for rainy days with nothing serious to fix/set up.

**Comment by jakubgs** [comment]
Fair.

**Comment by jakubgs** [comment]
I tried it on our keychain and didn't change the `md5` hash of the keychain:
```sh
administrator@macos-03.ms-eu-dublin.ci.misc:~ % md5 nim-status-client.keychain-db    
MD5 (nim-status-client.keychain-db) = 3bd9d4c85e4702236317a7535abb41bd

administrator@macos-03.ms-eu-dublin.ci.misc:~ % security set-key-partition-list -S apple-tool:,apple: -s -k ${KEYCHAIN_PASS} nim-status-client.keychain-db
...

administrator@macos-03.ms-eu-dublin.ci.misc:~ % md5 nim-status-client.keychain-db                                                                         
MD5 (nim-status-client.keychain-db) = 3bd9d4c85e4702236317a7535abb41bd
```

**Comment by jakubgs** [comment]
I tested a different version of the `set-key-partition-list` command that adds a `:codesign` app ID:
```
security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k ${KEYCHAIN_PASS} main.keychain-db
```
And it seems to have worked: https://ci.status.im/job/nim-status-client/job/macos/81/console

I also extended the docs with additional Keychain configuration steps: https://github.com/status-im/infra-docs/commit/9814d8dc

**Comment by jakubgs** [comment]
HOLY FUCK, first successful build: https://ci.status.im/job/nim-status-client/job/macos/83/
```
13:22:03  ### Signing target...
13:22:03  pkg/Status.dmg: signed  []
13:22:03  
13:22:03  ### Verifying signature...
13:22:04  pkg/Status.dmg: valid on disk
13:22:04  pkg/Status.dmg: satisfies its Designated Requirement
```
Now I just need to upload the DMG.

**Comment by jakubgs** [comment]
Oh wow, it think I solved it. The issue was that the keychain search list had entries for the local keychain file:
```
14:12:50  ### Adding keychain to search list...
14:12:50      "/Users/jenkins/nim-status-client.keychain-db"
14:12:50      "/Users/jenkins/Library/Keychains/login.keychain-db"
14:12:50      "/Users/jenkins/nim-status-client.keychain-db"
14:12:50      "/Users/jenkins/nim-status-client.keychain-db"
14:12:50      "/Users/jenkins/nim-status-client.keychain-db"
14:12:50      "/Users/jenkins/nim-status-client.keychain-db"
14:12:50      "****"
14:12:50      "/Library/Keychains/System.keychain"
```
Duplicate ones too. All I did was restore it to it's defaults by running:
```
jenkins@macos-03.ms-eu-dublin.ci.misc:~ % security list-keychains -s ""
jenkins@macos-03.ms-eu-dublin.ci.misc:~ % security list-keychains      
    "/Users/jenkins/Library/Keychains"
    "/Library/Keychains/System.keychain"
```
And this one worked fine with keychain from CI credentials: https://ci.status.im/job/nim-status-client/job/macos/88/

**Comment by jakubgs** [comment]
First working DMG: https://ci.status.im/job/nim-status-client/job/macos/86/artifact/pkg/Status.dmg
Build: https://ci.status.im/job/nim-status-client/job/macos/86/
Tested it on `macos-03`:
![working_status_dmg](https://user-images.githubusercontent.com/2212681/86124232-0f913480-badb-11ea-8dca-d7f5f60ad230.png)
Now the only issue is that this was signed with Keychain file that was already on the host.
I need to find what's causing it to fail when i use the Keychain from Jenkins credentials.

**Comment by jakubgs** [comment]
Linux still fails:
```
[2020-06-30T15:29:41.256Z] linuxdeployqt tmp/linux/dist/nim-status.desktop -no-translations -no-copy-copyright-files -qmldir=tmp/linux/dist/usr/ui -qmlimport=/opt/qt/5.14.0/gcc_64/qml -bundle-non-qt-libs
[2020-06-30T15:29:41.256Z] fuse: mount failed: Permission denied
[2020-06-30T15:29:41.522Z] open dir error: No such file or directory
```
But the `/dev/fuse` device appears to have the right permissions:
```
[2020-06-30T15:29:30.439Z] + ls -l /dev/fuse
[2020-06-30T15:29:30.439Z] crw-rw-rw- 1 root root 10, 229 Apr 28 15:11 /dev/fuse
```
But I assume the issue is caused by user remapping we use with Docker.

**Comment by jakubgs** [comment]
Oh shit, I fixed it by adding `--security-opt apparmor:unconfined` do `args` for docker:
https://ci.status.im/job/nim-status-client/job/linux/78/

**Comment by jakubgs** [comment]
The one remaining issue is the `npm` failures I get sometimes on the `Package` stage:
```
npm i

> fs-xattr@0.3.1 install /Users/jenkins/workspace/nim-status-client/macos/node_modules/fs-xattr
> node-gyp rebuild

ERROR:root:code for hash md5 was not found.
ERROR:root:code for hash sha1 was not found.
ERROR:root:code for hash sha224 was not found.
ERROR:root:code for hash sha256 was not found.
ERROR:root:code for hash sha384 was not found.
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "/usr/local/Cellar/node@10/10.12.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/Cellar/node@10/10.12.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/usr/local/Cellar/node@10/10.12.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/usr/local/Cellar/node@10/10.12.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "/usr/local/Cellar/node@10/10.12.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "/usr/local/Cellar/node@10/10.12.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 79, in CalculateVariables
  File "/usr/local/Cellar/node@10/10.12.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/xcode.py", line 7, in <module>
    import gyp.xcodeproj_file
  File "/usr/local/Cellar/node@10/10.12.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcodeproj_file.py", line 152, in <module>
    _new_sha1 = hashlib.sha1
AttributeError: 'module' object has no attribute 'sha1'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/Cellar/node@10/10.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/Cellar/node@10/10.12.0/bin/node" "/usr/local/Cellar/node@10/10.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jenkins/workspace/nim-status-client/macos/node_modules/fs-xattr
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fs-xattr@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fs-xattr@0.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
It appears random so far.

**Comment by michaelsbradleyjr** [comment]
On first round of research, this is the closes match I could find: https://stackoverflow.com/a/60040542

**Comment by jakubgs** [comment]
Yeah, that's it. I'm going to clean all workspaces and start from scratch to verify it's not something lingering from my experiments.

**Comment by jakubgs** [comment]
The issue appears to be connected to `macos-02`, so I don't think it's related to my branch:
```
Running on macos-01 in /Users/jenkins/workspace/nim-status-client/macos
```

**Comment by jakubgs** [comment]
Whelp. I did a force reinstallation of Command Line Tools on `macos-01` with:
```
administrator@macos-01.ms-eu-dublin.ci.misc:~ % sudo rm -rf /Library/Developer/CommandLineTools
administrator@macos-01.ms-eu-dublin.ci.misc:~ % xcode-select --install
```
And this seems to have fixed it. Retarded.

**Comment by jakubgs** [comment]
I created the PR: https://github.com/status-im/nim-status-client/pull/492/

**Comment by jakubgs** [comment]
This should be closed.
