### ISSUE TITLE
rename app name/title to say "Status Desktop"

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status-client#392]

**Comment by hydr063n** [comment]
Hey. Can I pick up this issue? I already have a fix ready. (Side note: am I 100% certain that this means only changing the title and not other meta data? Eg the name on the README.md or ui element `<message id="nim-status-client">` for instance)

![App title](https://i.imgur.com/28T2hj0.png)

**Comment by iurimatias** [comment]
@hydr063n yes absolutely. thank you for contributing :D
