### ISSUE TITLE
Wallet UI fixes

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status-client#472]
[_] wallet and chat titles are in different places
[_] padding should be 16px
[_] icons need to be updated
** we are using the same
[_] triangle in settings dropdown is in the wrong place
[_] send/receive icons are different in the design
[_] tabs should have blue bars only on active tab
[_] add/remove tokens scroll goes out of bounds

**Comment by jrainville** [comment]
Fixed in https://github.com/status-im/nim-status-client/pull/577

"triangle in settings dropdown is in the wrong place" was not fixed there, because it requires a PopupMenu refactor/improvement, because it cannot go out of the window
