### ISSUE TITLE
importing seed phrase isn't display correct username

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status-client#476]
1. on the onboarding/login, import the seed phrase from the mobile
2. go to profile

result: username is not matching the one in mobile

note: this is a regression likely due to a change we did on which account to use/select

**Comment by richard-ramos** [comment]
Can't reproduce the issue. I generated a new account on status-react: `require client spirit season hunt debris mother resemble diary draft august draw` which generates the username "Upset Average Trumpeterbird" and i get the same on desktop

**Comment by richard-ramos** [comment]
oh! I could reproduce the issue. It happens when you restore an account and you already had one
