### ISSUE TITLE
support 'compact' UI mode

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status-client#514]
this should be a toggle in advanced settings that switches the chat API to the compact version
might be a good oportunity to refactor the Message.qml code with a StackLayout

**Comment by jrainville** [comment]
From Iuri: "there is no design for this, so I leave it to you to what you think looks nice/better lol
but the basic idea is
- sidebar, channel/contact list has smaller height and font and no last message preview (basically like a discord/slack)
- main chat uses the entire width (currently the ballons only take half the screen of have a certain max)"
