### ISSUE TITLE
User stickers should be kept in a cache

### ISSUE THREAD

**Issue by richard-ramos** [status-im/nim-status-client#585]
In the mobile app once you buy a sticker, you'll have those available even if the app is offline. 
With the current implementation, `status_stickers.getBalance` is being called on login to obtain the sticker packs, and this function will fail when the internet connection is not available.

**Comment by emizzle** [comment]
Once a sticker pack is purchased, it will also be installed. Installed sticker packs will be retrievable without an internet connection, as they are stored in the `stickers/packs-installed` setting of status-go.

**Comment by richard-ramos** [comment]
I see. Indeed `self.status.chat.getInstalledStickerPacks()` is returning the sticker pack information, albeit later in the code `self.status.chat.getAvailableStickerPacks()` queries the contract, and depending on the result of this function, the sticker will be added to the view.

To fix this, we need to add the installed packs to the UI without depending on this contract call. Also, the images need to be kept in a local storage to avoid having to download them from IPFS

**Comment by emizzle** [comment]
On hold due to https://github.com/status-im/nim-status-client/issues/996.
