### ISSUE TITLE
Implement loading state UI: Obtain sticker packs when clicking on (+)

### ISSUE THREAD

**Issue by richard-ramos** [status-im/nim-status-client#586]
Instead of loading the sticker market packs on login, these should be obtained when you click on the (+) button on the stickers dialog. That way the contract will be queried to obtain the latest sticker packs available always and not only when you login.

In addition, this dialog should be aware if the application is connected or not. Only displaying the installed stickers if internet connection is not available as well as the last information cached from the contract, along with a loading indicator. (See the mobile app for the intended behavior).

**Comment by emizzle** [comment]
Should implement the “loading” state of the sticker market in the design.
