### ISSUE TITLE
MacOS: Use system color

### ISSUE THREAD

**Issue by decanus** [status-im/nim-status-client#599]
So with MacOS you can get the system color, ideally the color scheme would be set to the system color on startup, see: https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/dark-mode/

It looks like Qt already supports this?

References:
 - https://github.com/spyder-ide/spyder/issues/10026
 - https://bugreports.qt.io/browse/QTBUG-68850
 - https://bugreports.qt.io/browse/QTBUG-70346

**Comment by emizzle** [comment]
Needs an additional setting in `status-go`. See discussion: https://discordapp.com/channels/624205794384281629/697843216048717905/760013197842579487.
