### ISSUE TITLE
feature: enable test tokens in wallet > assets

### ISSUE THREAD

**Issue by emizzle** [status-im/nim-status-client#613]
Token assets are currently hardcoded in QML (https://github.com/status-im/nim-status-client/blob/master/ui/app/AppLayouts/Wallet/data/Tokens.qml) and should allow for testnet token lists as well.

In particular, STT is of use as it can be used to purchase sticker packs and would be helpful to appear in the asset list so it can be sent/received to/from other accounts.

**Comment by richard-ramos** [comment]
@emizzle:
> there is some logic in libstatus/contracts.nim that gets contracts by network. it should be merged with the token list somehow (like create one base ERC-20 contract and have all the tokens inherit from it). That way, we will always get the correct contract with getContract(“Dai”) for example

**Comment by emizzle** [comment]
Related issue: https://github.com/status-im/nim-status-client/issues/871
