### ISSUE TITLE
Notification improvement

### ISSUE THREAD

**Issue by richard-ramos** [status-im/nim-status-client#625]
@rramos:
> isnt it possible of instead creating a new notification for each message,
to create a single notification and update its content
and handle visibility?
there will always be a single notification object in memory, but hidden after a timeout

@iurimatias:
> possibly, probably
but the main challenge with all this
was the flags

@iurimatias
> any improvements to this needs to take into account these 2 scenarios
1 - if the app is background, the notification needs to show up above all windows
2- if the app is focused, and a notification comes in, it should not block the input, or freeze the main app

**Comment by jrainville** [comment]
I think this was fixed
