### ISSUE TITLE
Context menu for 1:1 chats

### ISSUE THREAD

**Issue by richard-ramos** [status-im/nim-status-client#631]
This contact menu should appear when right clicking on a 1:1 chat in the channel list, and when clicking on the title or the three dots in the 1:1 chat.

![Screenshot from 2020-07-23 08-39-39](https://user-images.githubusercontent.com/1106587/88287326-23861b80-ccc0-11ea-81b2-64703e6dce36.png)

https://www.figma.com/file/Mr3rqxxgKJ2zMQ06UAKiWL/%F0%9F%92%AC-Chat%E2%8E%9CDesktop?node-id=613%3A4998

**Comment by jrainville** [comment]
This is pretty much done, but we're missing the context menu on the three dots on the top bar

**Comment by jrainville** [comment]
There are small differences between each type of chat:

Group chat:
![image.png](https://images.zenhubusercontent.com/5ea70e106499d53d00627c49/652da38a-e4b4-45da-8c86-dee44e0e7db1)

Public chat:
![image.png](https://images.zenhubusercontent.com/5ea70e106499d53d00627c49/1983ba85-d760-4280-bcca-e8010e9918f6)

Private 1:1 chat:
![image.png](https://images.zenhubusercontent.com/5ea70e106499d53d00627c49/4e61748e-c5ed-4a0a-abbb-19a2d74b2bed)
