### ISSUE TITLE
AddressInput.qml: check for valid ENS name

### ISSUE THREAD

**Issue by emizzle** [status-im/nim-status-client#718]
Currently, the `AddressInput` component only checks for a valid ENS address by validating if the input passes an email and domain name regex. This should be updated to check if the ENS address resolves to a valid address. This is a long operation and needs to be handled accordingly in the UI.

**Comment by PascalPrecht** [comment]
Landed via https://github.com/status-im/nim-status-client/pull/867/commits/d4f3fad2feed0110ff3220108761185d25bfdb03
