### ISSUE TITLE
fix account generation in the wallet

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status-client#765]

**Comment by jrainville** [comment]
This was already fixed previously

Phone accounts
![Screenshot_20200825-145434.png](https://images.zenhubusercontent.com/5ea70e106499d53d00627c49/943df2c9-5647-4df7-a787-8dbc934f2f7f)

Desktop accounts
![image.png](https://images.zenhubusercontent.com/5ea70e106499d53d00627c49/2f79c3f3-df6e-4826-b60c-4f9a96fbef88)
