### ISSUE TITLE
Mentions issues

### ISSUE THREAD

**Issue by rasom** [status-im/nim-status-client#769]
- It is case sensitive, e.g. `"@roman"` mention will be successfully replaced with pubkey, but `"@Roman"` won't be

- When select some suggestion from the list, input field is messed up a bit.
  **Expected behaviour:** 
  1. `@roman` is added to contacts
  2. Start typing `"@ro"` in chat
  3. Press on `roman.stateofus.eth`
  4. See `"@roman.stateofus.eth "` (likely it should be `"@roman "`, but that's another issue) in text input with cursor after the last white space. 

  **Actual behaviour:**
  1. `@roman` is added to contacts
  2. Start typing `"@ro"` in chat
  3. Press on `roman.stateofus.eth`
  4. Input is changed to `"@roman.stateofus.eth ro"`, cursor is placed before the last `"o"`

  ![ensment1](https://user-images.githubusercontent.com/2364994/91283804-be788680-e793-11ea-998d-462c1e90217b.gif)

- When select the name from suggestions it is replaced with a full ENS name with domain, but after sending only actual username is replaced with pubkey. So probably better to use username without domain there 

  ![ensment2](https://user-images.githubusercontent.com/2364994/91284255-537b7f80-e794-11ea-8f54-98303d8a6a06.gif)

- Three words usernames are not replaced with pubkey although this is recommended by spec https://github.com/status-im/specs/pull/105/files#diff-d6415c46ddd0bb7309e7ca0f73876702R169 

- Three words usernames are not suggested unless there is a ENS name for the same pub key (I would suggest showing three words name along with ENS in suggestions)

- Suggestions are not shown right after loading messages and ENS names, you have to switch chats and only then suggestions will appear on typing.
  **Steps to reproduce:**
  1. Create a new acc
  2. Open `#status` channel 
  3. Try to suggest any of resolved ENS

- If two consecutive mentions are added to input without a whitespace between them resulting message does not recognise the first replaced pub key, so probably a whitespace should be added there during ens to pub key replacement
  
  ![bridge](https://user-images.githubusercontent.com/2364994/91289816-7eb59d00-e79b-11ea-80e3-bc32bc6ce5e3.gif)

- similar problem happens when there is no whitespace after mention but there is some non-word character: mention is parsed but then it won't be recognised in the message
  
  ![bridge2](https://user-images.githubusercontent.com/2364994/91290402-3a76cc80-e79c-11ea-9ed4-ab3a300132ec.gif)

**Comment by rasom** [comment]
one more problem:
If there is no whitespace before `"@"` suggestions won't be shown
![foobridge](https://user-images.githubusercontent.com/2364994/91320174-e7b20a80-e7c5-11ea-84cc-c374f0568ef6.gif)

**Comment by PascalPrecht** [comment]
> hree words usernames are not replaced with pubkey although this is recommended by spec https://github.com/status-im/specs/pull/105/files#diff-d6415c46ddd0bb7309e7ca0f73876702R169

This is working

**Comment by PascalPrecht** [comment]
> If there is no whitespace before "@" suggestions won't be shown
As discussed offline, this is by design

**Comment by PascalPrecht** [comment]
> Three words usernames are not suggested unless there is a ENS name for the same pub key (I would suggest showing three words name along with ENS in suggestions)

Actually this is more dependent who's in your contacts. E.g. if you add a contact that hasn't added you back (and therefore you don't see the EnsName yet), you'll see that contact show up in the suggestions with the three name alias

But yes, show both would be better.

**Comment by PascalPrecht** [comment]
Alright, most of the issues described here are handled in https://github.com/status-im/nim-status-client/pull/779

Things left to do:

- Ensure aliases, ensName and userName only get replaced with pubKey when there's a whitespace in front of them. Need to adjust these for that: https://github.com/status-im/nim-status-client/blob/ef22fb348dab00df8b032a47c4bfc050f52349fe/src/app/chat/view.nim#L114-L116 (/cc @emizzle might need to pick your brain for that)
- Show user Alias next to EnsUsername in SuggestionBox template. This isn't supported right now because it only renders text. To keep it flexible enough I need to refactor it so it accepts a custom view component that decides what should be rendered.

**Comment by PascalPrecht** [comment]
Fixed another bug in #797 where mentions without word boundary are replaced (which shouldn't be the case)
