### ISSUE TITLE
Send Transaction Modal feat: test sending of non-eth tokens

### ISSUE THREAD

**Issue by emizzle** [status-im/nim-status-client#788]
Test sending of tokens. This requires that token contracts are setup for testnet. Right now, the contract addresses they reference are for mainnet only.

**Comment by richard-ramos** [comment]
This functionality should take in account the number of decimals the token might have

There's a hex2token function that does the conversion from hex to a numeric string, doing the calculation with the number of decimals. We need the inverse for this functionality.
