### ISSUE TITLE
Status freezes on MACOS resume from standby

### ISSUE THREAD

**Issue by tbenr** [status-im/nim-status-client#819]
I put the mac on standby while status desktop (alpha4) was running.
When I resumed the mac, all apps was correctly working but status remain freezed.
I killed it. Here is the dump: https://gist.github.com/tbenr/e59ea6d612fafba3201cc8b00043af1a

**Comment by flexsurfer** [comment]
looks similar to https://github.com/status-im/nim-status-client/issues/705

**Comment by iurimatias** [comment]
I cannot replicate this in beta.1, please reopen if you're still experiencing this
