### ISSUE TITLE
wallet should display fiat balances with commas for easier reading

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status-client#845]
e.g random address found 0x94624766edabf74bef1f6b2baf97ad7c203b1d0d
it should display $1,253,034.44 but currently it's displaying $1253034.44

**Comment by PascalPrecht** [comment]
This is actually dependant on the selected locale. E.g. some countries use `.` as separators and `,` as delimiter, other countries do it exactly the other way around..

I looked in Nim's manual but it doesn't look like the language comes with a built-in solution for this.. would've been cool if there was an equivalent to JavaScript's `Number.prototype.toLocaleString()`

**Comment by PascalPrecht** [comment]
Tried using `toLocaleString()` inside QML but it seems that API is a noop in that environment. Looking into nim based solution
