### ISSUE TITLE
When buying stickers the Continue button never becomes active

### ISSUE THREAD

**Issue by hydr063n** [status-im/nim-status-client#926]
Continue buttons is never clickable even when user has enough SNT

steps to reproduce
- Click stickers
- Click add stickers
- Click on a sticker that requires snt

![](https://i.imgur.com/bDTGd2F.png)

**Comment by emizzle** [comment]
@hydr063n, I wasn't able to reproduce this, could you please confirm if this is still an issue on latest master?

**Comment by hydr063n** [comment]
Hey @emizzle , Yes this issue still occurs for me. The following RPC call gets invoked when I click on buy sticker and then the authorize popup opens. The RPC doesn't return a response
```
DBG 2020-09-30 15:20:41+02:00 callPrivateRPC                             topics="rpc" tid=199346 file=core.nim:20 rpc_method=eth_estimateGas
```

Ther was one time where the RPC responded with an error, but I am unable to get this error again. The RPC call most of the time doesn't return a response or timeout
```
DBG 2020-09-30 15:06:57+02:00 callPrivateRPC                             topics="rpc" tid=198748 file=core.nim:20 rpc_method=eth_estimateGas
ERR 2020-09-30 15:06:57+02:00 rpc response error                         topics="rpc" tid=198748 file=core.nim:24 result="{\"jsonrpc\":\"2.0\",\"id\":0,\"error\":{\"code\":-32000,\"message\":\"gas required exceeds allowance (12474981) or always failing transaction\"}}"
```

This debug has a window of about 30 minutes where nothing was returned
```
DBG 2020-09-30 15:20:41+02:00 callPrivateRPC                             topics="rpc" tid=199346 file=core.nim:20 rpc_method=eth_estimateGas
.
.
DBG 2020-09-30 15:55:52+02:00 callPrivateRPC                             topics="rpc" tid=199346 file=core.nim:20 rpc_method=eth_estimateGas
.
.
DBG 2020-09-30 15:58:04+02:00 callPrivateRPC                             topics="rpc" tid=199346 file=core.nim:20 rpc_method=eth_estimateGas
```

**Comment by emizzle** [comment]
@hydr063n, is this mainnet? Which platform are you using?

**Comment by emizzle** [comment]
Fixed in https://github.com/status-im/nim-status-client/pull/1074
