### ISSUE TITLE
App Crashes after "Group Chat" is created

### ISSUE THREAD

**Issue by simonricoo** [status-im/nim-status-client#969]
Quit Status if you have it opened -> Open Status -> Create a Group Chat -> App Crashes after I typed a name of the group
Version - Alpha 5

Video zipped bellow
[Screen Recording 2020-09-22 at 10.08.06.zip](https://github.com/status-im/nim-status-client/files/5259906/Screen.Recording.2020-09-22.at.10.08.06.zip)

**Comment by iurimatias** [comment]
@simonricoo I cannot replicate so it seems to have been fixed in meanwhile, please let me know if not.
